# Site settings
title: Zheyuan Gong
description: Zheyuan Gong's web
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zheyuan Gong
user_description: I am currently a PhD student in the Department of Mechanical and Industrial Engineering, University of Toronto. Before that, I received my M.Eng. and B.Eng. degree in Beihang University, in 2019 and 2016, respectively.
user_title: Ph.D. student
email: zygong@mie.utoronto.ca
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "Zheyuan Gong"

exclude: ['package.json', 'src' , 'node_modules']
