# Site settings
title: Zheyuan Gong
description: Zheyuan Gong's web
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zheyuan Gong
user_description: I am currently a Ph.D. student at the Advanced Micro and Nanosystems Laboratory (AMNL), University of Toronto, under the supervision of Prof. Yu Sun. My research interest locates in medical microrobotics. Before that, I received my M.Eng. and B.Eng. degree in Beihang University, in 2019 and 2016, respectively. During this period, I explored the underwater soft robotics. My works include underwater soft manipulator, octopus gripper, remora adhesive disc, soft gripper, etc.
user_title: Ph.D. student
email: zygong@mie.utoronto.ca
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "Zheyuan Gong"

exclude: ['package.json', 'src' , 'node_modules']
